# Generated by Django 5.0.6 on 2024-07-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_joined_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_date',
        ),
        migrations.AddField(
            model_name='user',
            name='id_unique',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(null=True),
        ),
    ]
