# Generated by Django 5.0.6 on 2024-07-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_joined_date_user_id_unique_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_unique',
            field=models.SmallIntegerField(null=True),
        ),
    ]
