# Generated by Django 5.0.6 on 2024-07-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.SmallIntegerField(null=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(null=True)),
                ('category', models.CharField(max_length=250)),
                ('date_published', models.DateTimeField(null=True)),
            ],
        ),
    ]
