# Generated by Django 5.0.6 on 2024-07-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id_post',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_unique',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_c', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(null=True)),
                ('post_iD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.post')),
                ('user_iD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
