# Generated by Django 5.0.6 on 2024-07-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_post_id_comment_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_id',
        ),
    ]
