# Generated by Django 5.0.6 on 2024-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_post_comment_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
