# Generated by Django 5.0.6 on 2024-07-12 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_comment_comment_id_post_post_id_user_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='id_post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='id_user',
        ),
    ]
