# Generated by Django 5.0.6 on 2024-07-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_post_id_comment_id_post_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.SmallIntegerField(null=True)),
                ('name_category', models.CharField(max_length=250)),
            ],
        ),
    ]
