# Generated by Django 5.0.6 on 2024-07-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_post',
            new_name='idpost',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='id_user',
            new_name='iduser',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_id',
            new_name='postid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='userid',
        ),
    ]
